version: '3.8'

services:
  alchemy-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env
    environment:
      - NODE_ENV=test
    networks:
      - test-network

  oracle-alchemy-test:
    build:
      context: ./oracle-service
      dockerfile: Dockerfile
    env_file:
      - oracle-service/.env
    environment:
      - NODE_ENV=test
    command: node test-alchemy-oracle.js
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 